base:
  seed: 42

data_load:
  day_csv: 'data/raw/day.csv'
  hour_csv: 'data/raw/hour.csv'

data_split:
  test_size: 0.2
  trainset_path: 'data/processed/train_hour.csv'
  testset_path: 'data/processed/test_hour.csv'

train:
  cv: 3
  estimator_name: logreg
  C: 0.001
  max_iter:100
  solver: 'lbfgs'
  multi_class: 'multinomial'
  model_path: models/model.joblib
